jobs:
  - job: swift_devtools__${{ parameters.proc }}_deb
    variables:
    steps:
      - checkout: self
        displayName: 'checkout compnerd/swift-build'
      - checkout: apple/swift-cmark
        displayName: 'checkout apple/swift-cmark'
      - download: current
        artifact: devtools-linux-${{ paramters.host }}
      - script: |
          mkdir -p $(Build.StagingDirectory)/swift-devtools
          rsync -v -a -l $(Pipeline.Workspace)/devtools-linux-${{ parameters.host }}/Library $(Build.StagingDirectory)/swift-devtools/Library
        displayName: 'cleanup image'
      - script: |
          mkdir -p $(Build.StagingDirectory)/swift-devtools/DEBIAN
          sed -e "s/Version:/& $(Build.BuildId)/" $(Build.SourcesDirectory)/swift-build/debian/${{ parameters.platform }}-devtools > $(Build.StagingDirectory)/swift-devtools/DEBIAN/control

          cd $(Build.StagingDirectory)
          fakeroot dpkg-deb --build swift-devtools $(Build.StagingDirectory)
        displayName: 'package'
      - publish: $(Build.StagingDirectory)/swift-devtools_$(Build.BuildId)_${{ parameters.proc }}.deb
        artifact: swift-devtools_$(Build.BuildId)_${{ parameters.proc }}.deb
      - script: |
          cd $(Build.StagingDirectory)
          curl -F swift-devtools=@swift-devtools_$(Build.BuildId)_${{ parameters.proc }}.deb https://$(GEMFURY_PASSWORD)@push.fury.io/compnerd
        displayName: 'upload to gemfury'
        enabled: false
