# parameters:
# arch: [ 'aarch64' | 'x86_64' ]
# host: [ 'arm64' | 'x64' ]
# platform: [ 'android | 'win' ]

jobs:
  - job: ${{ parameters.platform }}_${{ parameters.host }}
    variables:
      icu.version: 64
      install.directory: $(Build.StagingDirectory)\Library\icu-$(icu.version)
      icu.release: maint/maint-$(icu.version)
      icu.build_tools: ${{ eq(parameters['build'], 'x64') }}
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: |
          git clone --quiet --depth 1 --single-branch --branch $(ICU.Release) https://github.com/unicode-org/icu.git
          copy $(Build.SourcesDirectory)\cmake\ICU\CMakeLists.txt icu\icu4c
        displayName: 'Fetch Sources'
      - ${{ if eq(parameters['platform'], 'windows') }}:
        - task: BatchScript@1
          inputs:
            filename: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\\Tools\VsDevCmd.bat
            arguments: -no_logo -arch=${{ parameters.host }} -host_arch=x64
            modifyEnvironment: true
          displayName: 'vcvarsall.bat'
        - task: CMake@1
          inputs:
            workingDirectory: $(Build.StagingDirectory)\icu
            cmakeArgs: $(Build.SourcesDirectory)\icu\icu4c -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=$(install.directory)\usr -DBUILD_SHARED_LIBS=YES -DBUILD_TOOLS=$(icu.build_tools)
          displayName: 'Configure ICU'
      - ${{ if eq(parameters['platform'], 'android') }}:
        - task: BatchScript@1
          inputs:
            filename: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\\Tools\VsDevCmd.bat
            arguments: -no_logo -arch=x64 -host_arch=x64
            modifyEnvironment: true
          displayName: 'vcvarsall.bat'
        - task: CMake@1
          inputs:
            workingDirectory: $(Build.StagingDirectory)\icu
            cmakeArgs: $(Build.SourcesDirectory)\icu\icu4c -G Ninja -C $(Build.SourcesDirectory)\cmake\caches\android-${{ parameters.arch }}.cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=$(install.directory)\usr -DBUILD_SHARED_LIBS=YES
          displayName: 'Configure ICU'
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\icu
        displayName: 'Build ICU'
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\icu --target install
        displayName: 'Install ICU'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.StagingDirectory)\Library
          artifactName: icu-${{ parameters.platform }}-${{ parameters.host }}