jobs:
  - job: ${{ parameters.host }}
    variables:
      install.directory: $(Build.StagingDirectory)/zlib-${{ parameters.platform }}-${{ parameters.host }}/Library/zlib-$(zlib.version)
    steps:
      - checkout: self
        displayName: checkout compnerd/swift-build

      - checkout: madler/zlib
        displayName: checkout madler/zlib

      - task: BatchScript@1
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: VsDevCmd
        inputs:
          filename: C:/Program Files (x86)/Microsoft Visual Studio/${{ parameters.VisualStudio }}/Common7/Tools/VsDevCmd.bat
          arguments: -no_logo -arch=${{ parameters.host }} -host_arch=x64
          modifyEnvironment: true

      - script: |
          curl -qL https://apt.kitware.com/keys/kitware-archive-latest.asc | sudo apt-key add -
          echo 'deb https://apt.kitware.com/ubuntu/ bionic main' | sudo tee -a /etc/apt/sources.list
          sudo apt-get -yq update
          sudo apt-get -yq install cmake ninja-build
        condition: eq( variables['Agent.OS'], 'Linux' )
        displayName: Install Dependencies

      - task: CMake@1
        displayName: Configure zlib
        inputs:
          cmakeArgs:
            -G Ninja
            -S $(Build.SourcesDirectory)/zlib
            -B $(Build.BinariesDirectory)/zlib
            -C $(Build.SourcesDirectory)/swift-build/cmake/caches/${{ parameters.platform }}-${{ parameters.arch }}.cmake
            -D BUILD_SHARED_LIBS=NO
            -D BUILD_TESTING=NO
            -D CMAKE_BUILD_TYPE=MinSizeRel
            -D CMAKE_INSTALL_PREFIX=$(install.directory)/usr
            -D CMAKE_POSITION_INDEPENDENT_CODE=YES

      - task: CMake@1
        displayName: Build zlib
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/zlib

      - task: CMake@1
        displayName: Install zlib
        inputs:
          cmakeArgs: --build $(Build.BinariesDirectory)/zlib --target install

      - publish: $(Build.StagingDirectory)/zlib-${{ parameters.platform }}-${{ parameters.host }}
        artifact: zlib-${{ parameters.platform }}-${{ parameters.host }}
