name: 'android SDK'
jobs:
  - template: templates/android-sdk.yml
    parameters:
      arch: 'armv7'
      arch.alt: 'armv7'
      build: 'arm'
      triple: 'armv7-unknown-linux-androideabi'

  - template: templates/android-sdk.yml
    parameters:
      arch: 'arm64'
      arch.alt: 'aarch64'
      build: 'arm64'
      triple: 'aarch64-unknown-linux-android'

