name: 'android SDK'
variables:
  install.directory: $(Build.StagingDirectory)\Library\Developer\Platforms\Android.platform\Developer\SDKs\Android.sdk\usr
  curl.directory: $(System.ArtifactsDirectory)\curl-android-arm64\libcurl-development
  icu.directory: $(System.ArtifactsDirectory)\icu-android-arm64\ICU-64
  xml2.directory: $(System.ArtifactsDirectory)\xml2-android-arm64\libxml2-development
  toolchain.directory: $(System.ArtifactsDirectory)\toolchain\Developer\Toolchains\unknown-Asserts-development.xctoolchain
jobs:
  - job: android
    steps:
      - script: |
          git config --global user.name 'builder'
          git config --global user.email 'root@compnerd.org'

          git clone --quiet --depth 1 --single-branch https://github.com/apple/swift-llvm llvm
          git clone --config core.autocrlf=false --config core.symlinks=true --quiet --depth 1 --single-branch https://github.com/apple/swift swift

          git clone --quiet --depth 1 --single-branch https://github.com/apple/swift-corelibs-libdispatch swift-corelibs-libdispatch
          git clone --quiet --depth 1 --single-branch https://github.com/apple/swift-corelibs-foundation swift-corelibs-foundation
          git clone --quiet --depth 1 --single-branch https://github.com/apple/swift-corelibs-xctest swift-corelibs-xctest
        displayName: 'Fetch Sources'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: specific
          project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
          allowPartiallySucceededBuilds: true
          pipeline: 1
          artifactName: 'toolchain'
          downloadPath: '$(System.ArtifactsDirectory)'
        displayName: 'Install toolchain'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: specific
          project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
          allowPartiallySucceededBuilds: true
          pipeline: 9
          artifactName: 'icu-android-arm64'
          downloadPath: '$(System.ArtifactsDirectory)'
        displayName: 'Install ICU'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: specific
          project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
          pipeline: 10
          allowPartiallySucceededBuilds: true
          artifactName: 'xml2-android-arm64'
          downloadPath: '$(System.ArtifactsDirectory)'
        displayName: 'Install XML2'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: specific
          project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
          pipeline: 11
          allowPartiallySucceededBuilds: true
          artifactName: 'curl-android-arm64'
          downloadPath: '$(System.ArtifactsDirectory)'
        displayName: 'Install CURL'
      - task: BatchScript@1
        inputs:
          filename: C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat
          arguments: -no_logo -arch=x64
          modifyEnvironment: true
        displayName: 'vsvarsall.bat'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '2.7.x'
      - script: |
          echo "##vso[task.setvariable variable=PATH]$(System.ArtifactsDirectory)\\toolchain\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\bin;%PATH%"
        displayName: 'Update PATH'
      - task: CMake@1
        inputs:
          workingDirectory: $(Build.StagingDirectory)\llvm
          cmakeArgs: -G Ninja -C $(Build.SourcesDirectory)\cmake\caches\android-aarch64.cmake $(Build.SourcesDirectory)\llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_HOST_TRIPLE=aarch64-unknown-linux-android
        displayName: 'Configure LLVM'
      - task: CMake@1
        inputs:
          workingDirectory: $(Build.StagingDirectory)\swift-stdlib
          cmakeArgs: -G Ninja -C $(Build.SourcesDirectory)\cmake\caches\android-aarch64.cmake -C $(Build.SourcesDirectory)\cmake\caches\swift-stdlib-android-aarch64.cmake $(Build.SourcesDirectory)\swift -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=$(Build.StagingDirectory)\llvm\lib\cmake\llvm -DSWIFT_NATIVE_SWIFT_TOOLS_PATH=$(toolchain.directory)\usr\bin -DCMAKE_INSTALL_PREFIX=$(install.directory) -DSWIFT_ANDROID_aarch64_ICU_UC_INCLUDE=$(icu.directory)\usr\include\unicode -DSWIFT_ANDROID_aarch64_ICU_UC=$(icu.directory)\usr\lib\libicuuc.so -DSWIFT_ANDROID_aarch64_ICU_I18N_INCLUDE=$(icu.directory)\usr\include -DSWIFT_ANDROID_aarch64_ICU_I18N=$(icu.directory)\usr\lib\libicuin.so
        displayName: 'Configure Swift standard library'
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\swift-stdlib
        displayName: 'Build Swift standard library'
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\swift-stdlib --target install
        displayName: 'Install Swift standard library'
      - task: CMake@1
        inputs:
          workingDirectory: $(Build.StagingDirectory)\libdispatch
          cmakeArgs: -G Ninja -C $(Build.SourcesDirectory)\cmake\caches\android-aarch64.cmake $(Build.SourcesDirectory)\swift-corelibs-libdispatch -DSWIFT_ANDROID_SDK=$(Build.StagingDirectory)\Library\Developer\Platforms\Android.platform\Developer\SDKs\Android.sdk -C $(Build.SourcesDirectory)\cmake\caches\android-aarch64-swift-flags.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_SWIFT_COMPILER=swiftc -DCMAKE_INSTALL_PREFIX=$(install.directory) -DENABLE_TESTING=NO -DENABLE_SWIFT=YES
        displayName: 'Configure libdispatch'
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\libdispatch
        displayName: 'Build libdispatch'
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\libdispatch --target install
        displayName: 'Install libdispatch'
      - task: CMake@1
        inputs:
          workingDirectory: $(Build.StagingDirectory)\foundation
          cmakeArgs: cmake -G Ninja -C $(Build.SourcesDirectory)\cmake\caches\android-aarch64.cmake $(Build.SourcesDirectory)\swift-corelibs-foundation -DCMAKE_BUILD_TYPE=Release -DCMAKE_SWIFT_COMPILER=swiftc -DCMAKE_INSTALL_PREFIX=$(install.directory) -DCURL_LIBRARY=$(curl.directory)\usr\lib\libcurl.a -DCURL_INCLUDE_DIR=$(curl.directory)\usr\include -DICU_INCLUDE_DIR=$(icu.directory)\usr\include -DICU_UC_LIBRARY_RELEASE=$(icu.directory)\usr\lib\libicuuc.so -DICU_I18N_LIBRARY=$(icu.directory)\usr\lib\libicuin.so -DLIBXML2_LIBRARY=$(xml2.directory)\usr\lib\libxml2.a -DLIBXML2_INCLUDE_DIR=$(xml2.directory)\usr\include\libxml2 -DFOUNDATION_PATH_TO_LIBDISPATCH_SOURCE=$(Build.SourcesDirectory)\swift-corelibs-libdispatch -DFOUNDATION_PATH_TO_LIBDISPATCH_BUILD=$(Build.StagingDirectory)\libdispatch
        displayName: 'Configure Foundation'
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\foundation
        displayName: 'Build Foundation'
        continueOnError: true
      - task: CMake@1
        inputs:
          cmakeArgs: --build $(Build.StagingDirectory)\foundation --target install
        displayName: 'Install Foundation'
        continueOnError: true
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.StagingDirectory)\Library
          artifactName: sdk
