name: curl
jobs:
  - template: templates/curl.yml
    parameters:
      host: 'arm64'
      platform: 'windows'
      alt_platform: 'win'

  - template: templates/curl.yml
    parameters:
      host: 'x64'
      platform: 'windows'
      alt_platform: 'win'

  - template: templates/curl.yml
    parameters:
      arch: 'armv7'
      host: 'armeabi'
      platform: 'android'
      alt_platform: 'android'

  - template: templates/curl.yml
    parameters:
      arch: 'aarch64'
      host: arm64
      platform: 'android'
      alt_platform: 'android'

  - template: templates/curl.yml
    parameters:
      arch: 'x86_64'
      host: 'x64'
      platform: 'android'
      alt_platform: 'android'
