name: icu
jobs:
  - template: templates/icu.yml
    parameters:
      host: 'arm64'
      platform: 'win'

  - template: templates/icu.yml
    parameters:
      host: 'x64'
      platform: 'win'

  - template: templates/icu.yml
    parameters:
      arch: 'armv7'
      host: 'arm'
      platform: 'android'

  - template: templates/icu.yml
    parameters:
      arch: 'aarch64'
      host: arm64
      platform: 'android'

  - template: templates/icu.yml
    parameters:
      arch: 'x86_64'
      host: 'x64'
      platform: 'android'

  - template: templates/icu.yml
    parameters:
      arch: 'x86_64'
      host: 'x64'
      platform: 'linux'
      pool:
        pool: { name: 'FlowKey' }
