name: libxml2
jobs:
  - job: windows_arm64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: aarch64
      host: arm64
      platform: windows

      xml2.version: development
      install.directory: $(Build.StagingDirectory)\Library\libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=arm64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/libxml2.yml

  - job: windows_x64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: x86_64
      host: x64
      platform: windows

      xml2.version: development
      install.directory: $(Build.StagingDirectory)\Library\libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/libxml2.yml

  - job: android_armv7
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: armv7
      host: arm
      platform: android

      xml2.version: development
      install.directory: $(Build.StagingDirectory)\Library\libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/libxml2.yml

  - job: android_aarch64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: aarch64
      host: arm64
      platform: android

      xml2.version: development
      install.directory: $(Build.StagingDirectory)\Library\libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/libxml2.yml

  - job: android_x64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: x86_64
      host: x64
      platform: android

      xml2.version: development
      install.directory: $(Build.StagingDirectory)\Library\libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/libxml2.yml

  - job: linux_x64
    pool: FlowKey
    variables:
      arch: x86_64
      host: x64
      platform: linux

      xml2.version: development
      install.directory: $(Build.StagingDirectory)\Library\libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
    - template: templates/libxml2.yml
