name: libxml2
jobs:
  - template: templates/libxml2.yml
    parameters:
      build: arm64
      platform: 'windows'
      alt_platform: 'win'

  - template: templates/libxml2.yml
    parameters:
      build: x64
      platform: 'windows'
      alt_platform: 'win'

  - template: templates/libxml2.yml
    parameters:
      arch: 'armeabi'
      alt_arch: 'armv7'
      build: armeabi
      platform: 'android'
      alt_platform: 'android'

  - template: templates/libxml2.yml
    parameters:
      arch: 'arm64'
      alt_arch: 'aarch64'
      build: arm64
      platform: 'android'
      alt_platform: 'android'

  - template: templates/libxml2.yml
    parameters:
      arch: 'x64'
      alt_arch: 'x86_64'
      build: 'x64'
      platform: 'android'
      alt_platform: 'android'

