pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
resources:
  repositories:
    - repository: apple/swift-llbuild
      type: github
      name: apple/swift-llbuild
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-tools-support-core
      type: github
      name: apple/swift-tools-support-core
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-package-manager
      type: github
      name: apple/swift-package-manager
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/indexstore-db
      type: github
      name: apple/swift-package-manager
      ref: refs/heads/master
      endpoint: GitHub
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-devtools.yml
      - .ci/templates/linux-devtools.yml
jobs:
  - template: templates/linux-devtools.yml
    parameters:
      pool: FlowKey
      toolchain: 14

      arch: x86_64
      host: x64
      platform: linux
