pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-sdk.yml
      - .ci/templates/linux-sdk.yml
      - cmake/caches/linux-x86_64.cmake
      - cmake/caches/linux-x86_64-swift-flags.cmake
resources:
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: refs/heads/swift/master
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: refs/heads/master
      endpoint: GitHub
    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: refs/heads/master
      endpoint: GitHub
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/linux-sdk.yml
      - .ci/templates/linux-sdk.yml
      - cmake/caches/linux-x86_64.cmake
      - cmake/caches/linux-x86_64-swift-flags.cmake
jobs:
  - template: templates/linux-sdk.yml
    parameters:
      pool: FlowKey
      toolchain: 14

      arch: x86_64
      host: x64
      triple: x86_64-unknown-linux-gnu
