name: 'linux SDK'
jobs:
  - job: linux_x64
    variables:
      arch: x86_64
      host: x64
      triple: x86_64-unknown-linux-gnu

      toolchain.directory: $(System.ArtifactsDirectory)/toolchain/Developer/Toolchains/unknown-Asserts-development.xctoolchain
      curl.directory: $(System.ArtifactsDirectory)/curl-linux-$(host)/libcurl-development
      icu.version: 64
      icu.directory: $(System.ArtifactsDirectory)/icu-linux-$(host)/icu-$(icu.version)
      xml2.directory: $(System.ArtifactsDirectory)/xml2-linux-$(host)/libxml2-development
      install.directory: $(Build.StagingDirectory)/Library/Developer/Platforms/Linux.platform/Developer/SDKs/Linux.sdk/usr
      xctest.install.directory: $(Build.StagingDirectory)/Library/Developer/Platforms/Linux.platform/Developer/Library/XCTest-development/usr
    steps:
      - template: templates/linux-sdk.yml
