pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/macOS.yml
      - .ci/templates/toolchain.yml
resources:
  pipelines:
    - pipeline: icu
      source: 'ICU'
    - pipeline: tensorflow
      source: 'tensorflow'
  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/master
      endpoint: GitHub
    - repository: apple/swift
      type: github
      name: apple/swift
      ref: master
      endpoint: GitHub
    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: master
      endpoint: GitHub
    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: master
      endpoint: GitHub
    - repository: tensorflow/swift-apis
      type: github
      name: tensorflow/swift-apis
      ref: master
      endpoint: GitHub
schedules:
  - cron: "0 0 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/macOS.yml
      - .ci/templates/toolchain.yml
stages:
  - stage: toolchain
    jobs:
      - template: templates/toolchain.yml
        parameters:
          pool:
            vmImage: 'macOS-10.14'

          arch: x86_64
          host: x64
          platform: darwin

          triple: x86_64-apple-macosx10.14

          LLVM_OPTIONS: -DLLVM_INCLUDE_TESTS=NO
          LLDB_OPTIONS: -DLLDB_USE_SYSTEM_DEBUGSERVER=ON -DLLDB_INCLUDE_TESTS=NO -DLLDB_BUILD_FRAMEWORK=YES
          SWIFT_OPTIONS: -DSWIFT_INCLUDE_TESTS=NO

  - stage: package
    jobs:
      - template: templates/xctoolchain.yml
        parameters:
          pool:
            vmImage: 'macOS-10.14'

          arch: x86_64
          host: x64
          platform: darwin

          alias: swift
