name: sqlite
jobs:
  - template: templates/sqlite3.yml
    parameters:
      host: arm64
      platform: 'win'

  - template: templates/sqlite3.yml
    parameters:
      host: x64
      platform: 'win'

  - template: templates/sqlite3.yml
    parameters:
      arch: 'armv7'
      host: armeabi
      platform: 'android'

  - template: templates/sqlite3.yml
    parameters:
      arch: 'aarch64'
      host: arm64
      platform: 'android'

  - template: templates/sqlite3.yml
    parameters:
      arch: 'x86_64'
      host: 'x64'
      platform: 'android'

