name: sqlite
jobs:
  - template: template/sqlite3.yml
    parameters:
      build: arm64
      platform: 'windows'
      alt_platform: 'win'

  - template: template/sqlite3.yml
    parameters:
      build: x64
      platform: 'windows'
      alt_platform: 'win'

  - template: template/sqlite3.yml
    parameters:
      arch: 'armeabi'
      alt_arch: 'armv7'
      build: armeabi
      platform: 'android'
      alt_platform: 'android'

  - template: template/sqlite3.yml
    parameters:
      arch: 'arm64'
      alt_arch: 'arm64'
      build: arm64
      platform: 'android'
      alt_platform: 'android'

