name: sqlite
jobs:
  - template: templates/sqlite3.yml
    parameters:
      build: arm64
      platform: 'win'

  - template: templates/sqlite3.yml
    parameters:
      build: x64
      platform: 'win'

  - template: templates/sqlite3.yml
    parameters:
      arch: 'armv7'
      build: armeabi
      platform: 'android'

  - template: templates/sqlite3.yml
    parameters:
      arch: 'aarch64'
      build: arm64
      platform: 'android'

  - template: templates/sqlite3.yml
    parameters:
      arch: 'x86_64'
      build: 'x64'
      platform: 'android'

