name: toolchain
schedules:
  - cron: "0 0 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly Build"
jobs:
  - job: darwin_x64
    pool: 
      vmImage: macOS-10.14
    variables:
      arch: x86_64
      host: x64
      platform: darwin

      triple: x86_64-apple-macosx10.14

      install.directory: $(Build.StagingDirectory)/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr
    steps:
    - template: templates/toolchain.yml
