pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/ubuntu-18.04.yml
      - docker/Ubuntu-18.04/.dockerignore
      - docker/Ubuntu-18.04/Dockerfile
schedules:
  - cron: "0 8 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (8:00 AM) build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/ubuntu-18.04.yml
      - docker/Ubuntu-18.04/.dockerignore
      - docker/Ubuntu-18.04/Dockerfile
jobs:
  - job: ubuntu
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'compnerd/swift'
          command: 'buildAndPush'
          Dockerfile: 'docker/Ubuntu-18.04/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
