name: 'Windows SDK'
schedules:
  - cron: "0 6 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (6:00 AM) Build"
trigger:
  branches:
    - master
  paths:
    include:
      - .ci/windows-sdk.yml
      - .ci/templates/windows-sdk.yml
jobs:
  - template: templates/windows-sdk.yml
    parameters:
      arch: 'x86_64'
      build: 'x64'
      triple: 'x86_64-unknown-windows-msvc'

# - template: templates/windows-sdk.yml
#   parameters:
#     arch: 'aarch64'
#     build: 'arm64'
#     triple: 'aarch64-unknown-windows-msvc'
