name: zlib
schedules:
  - cron: "0 8 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (8:00 AM) Build"
jobs:
  - job: windows_arm64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: aarch64
      host: arm64
      platform: windows

      zlib.version: 1.2.11
      install.directory: $(Build.StagingDirectory)/Library/zlib-$(zlib.version)
      zlib.release: v1.2.11
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=arm64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/zlib.yml

  - job: windows_x64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: x86_64
      host: x64
      platform: windows

      zlib.version: 1.2.11
      install.directory: $(Build.StagingDirectory)/Library/zlib-$(zlib.version)
      zlib.release: v1.2.11
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/zlib.yml

  - job: android_armv7
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: armv7
      host: arm
      platform: android

      zlib.version: 1.2.11
      install.directory: $(Build.StagingDirectory)/Library/zlib-$(zlib.version)
      zlib.release: v1.2.11
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/zlib.yml

  - job: android_aarch64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: aarch64
      host: arm64
      platform: android

      zlib.version: 1.2.11
      install.directory: $(Build.StagingDirectory)/Library/zlib-$(zlib.version)
      zlib.release: v1.2.11
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/zlib.yml

  - job: android_x64
    pool:
      vmImage: 'windows-2019'
    variables:
      arch: x86_64
      host: x64
      platform: android

      zlib.version: 1.2.11
      install.directory: $(Build.StagingDirectory)/Library/zlib-$(zlib.version)
      zlib.release: v1.2.11
    steps:
    - task: BatchScript@1
      inputs:
        filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
        arguments: -no_logo -arch=x64 -host_arch=x64
        modifyEnvironment: true
      displayName: 'vcvarsall.bat'
    - template: templates/zlib.yml

  - job: linux_x64
    pool: FlowKey
    variables:
      arch: x86_64
      host: x64
      platform: linux

      zlib.version: 1.2.11
      install.directory: $(Build.StagingDirectory)/Library/zlib-$(zlib.version)
      zlib.release: v1.2.11
    steps:
    - template: templates/zlib.yml
