name: swift-argument-parser

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'revision to build'
        required: true
        default: 'refs/heads/main'

jobs:
  windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        include:
          - tag: 5.5-DEVELOPMENT-SNAPSHOT-2021-06-02-a
            branch: swift-5.5-branch

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v2
        with:
          repository: apple/swift-argument-parser
          ref: ${{ github.event.inputs.ref }}

      - name: build
        run: |
          swift build -c release

      - name: test
        run: |
          swift test -c release --enable-test-discovery
